name: Foundry CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: foundry-rs/foundry-toolchain@v1

      - name: Install deps
        run: forge install

      - name: Build
        run: forge build

      - name: Test
        run: forge test -vv

      - name: Gas report
        run: forge test --gas-report

      - name: Install Slither
        run: pip install slither-analyzer

      - name: Run Slither
        run: slither .  || true